service: ${env:SERVERLESS_SERVICE_NAME}-s3

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  logRetentionInDays: 3

custom:
  defaultStage: dev

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}-${self:provider.stage}
    LayerBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:LAYER_BUCKET_NAME}-${self:provider.stage}