name: deploy-dev

on:
  push:
    branches: 
      - develop
  
jobs:
  deploy-dev-sls:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        env:
          SECRET_HOGE_2: ${{secrets.CHECK}}
      - name: Use Python 3.8
        uses: actions/setup-python@v4
      
      - name: pre install
        run: make preinstall
