# 一旦はやりたいことを自分にわかるようになぞり書きする
name: deploy-dev
on:
  push:
    branches:
      - develop

env:
  NODE_VERSION: 16
  PYTHON_VERSION: 3.8

  LOG_LOCATION: /tmp/log/
  SLACK_COMMAND: /get-images

  SERVERLESS_SERVICE_NAME: new-imageautomation
  LAYER_BUCKET_NAME: new-imageautomation-layers
  # s3 に保存するリソース名。s3 配置時にEvent Bridgeが起動する。
  BUCKET_NAME: new-imageautomation-store
  S3_PREFIX: tmp-images_
  S3_SUFFIX: i.i.image.zip
  ZIP_FILE_NAME: i.i.image.zip

  OWNER: ${{ secrets.OWNER }}
  SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
  CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
  SHUTTERSTOCK_USERNAME: ${{ secrets.SHUTTERSTOCK_USERNAME }}
  SHUTTERSTOCK_PASSWORD: ${{ secrets.SHUTTERSTOCK_PASSWORD }}
  PIXTA_USERNAME: ${{ secrets.PIXTA_USERNAME }}
  PIXTA_PASSWORD: ${{ secrets.PIXTA_PASSWORD }}
  PIXTA_SITEKEY: ${{ secrets.PIXTA_SITEKEY }}
  CAPTCHA_APIKEY: ${{ secrets.CAPTCHA_APIKEY }}

  MY_VARIABLE1: "This will be overridden"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev-sls:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Use Node.js v${{ env.NODE_VERSION }}.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}.x

      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install serverless framework
        run: npm install -g serverless@3.28.1

      - name: Pre Install
        run: make preinstall

      - name: deploy Resources
        run: cd deploy && make deploy-dev ARG=resource

      - name: deploy receive
        run: cd deploy && make deploy-dev ARG=receive

      - name: deploy pixta
        run: cd deploy && make deploy-dev ARG=pixta

      - name: deploy shutterstock
        run: cd deploy && make deploy-dev ARG=shutterstock

      - name: deploy slack
        run: cd deploy && make deploy-dev ARG=slack

      - name: check-1
        run: echo $MY_VARIABLE1
      - name: check-2
        run: echo $MY_VARIABLE2
